services:
  cpp-docs:
    build: .
    container_name: cpp_docs
    ports:
      - "24354:24354"
    volumes:
      - .:/app
    command: sh -c "doxygen Doxyfile || true && python3 -m http.server 24354 --directory docs/html"
